In [3]:
import sys
import pandas as pd
import numpy as np

print("Environment setup successful!")
print("Python path:", sys.executable)
print("Pandas version:", pd.__version__)

Environment setup successful!
Python path: e:\BA Projects\Bank_Customer_Churn_Analysis\.venv\Scripts\python.exe
Pandas version: 3.0.6

In [4]:

import pandas as pd
from pathlib import Path

# Project directories
project_path = Path(r"E:\BA Projects\Bank_Customer_Churn_Analysis")
raw_path = project_path / "Data" / "Raw"

# Load Excel files
customer_df = pd.read_excel(raw_path / "customer_info.xlsx")
account_df = pd.read_excel(raw_path / "account_info.xlsx")

print("Customer_Info Shape:", customer_df.shape)
print("Account_Info Shape:", account_df.shape)

print("\nCustomer_Info Columns:")
print(customer_df.columns.tolist())

print("\nAccount_Info Columns:")
print(account_df.columns.tolist())

Customer_Info Shape: (10001, 8)
Account_Info Shape: (10002, 7)

Customer_Info Columns:
['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'EstimatedSalary']

Account_Info Columns:
['CustomerId', 'Balance', 'NumOfProducts', 'HasCrCard', 'Tenure', 'IsActiveMember', 'Exited']

In [6]:
print("\n CUSTOMER INFO:")
display(customer_df.head())

print("\n ACCOUNT INFO:")
display(account_df.head())

 CUSTOMER INFO:

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,EstimatedSalary
0,15634602,Hargrave,619,FRA,Female,42.0,2,€101348.88
1,15647311,Hill,608,Spain,Female,41.0,1,€112542.58
2,15619304,Onio,502,French,Female,42.0,8,€113931.57
3,15701354,Boni,699,FRA,Female,39.0,1,€93826.63
4,15737888,Mitchell,850,Spain,Female,43.0,2,€79084.1

 ACCOUNT INFO:

,CustomerId,Balance,NumOfProducts,HasCrCard,Tenure,IsActiveMember,Exited
0,15634602,€0.0,1,Yes,2,Yes,1
1,15634602,€0.0,1,Yes,2,Yes,1
2,15647311,€83807.86,1,Yes,1,Yes,0
3,15619304,€159660.8,3,No,8,No,1
4,15701354,€0.0,2,No,1,No,0

In [8]:
print("CUSTOMER INFO - DATA TYPES")
print(customer_df.info())

print("ACCOUNT INFO - DATA TYPES")

print(account_df.info())

CUSTOMER INFO - DATA TYPES
<class 'pandas.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10001 non-null  int64
 1   Surname          9998 non-null   str
 2   CreditScore      10001 non-null  int64
 3   Geography        10001 non-null  str
 4   Gender           10001 non-null  str
 5   Age              9998 non-null   float64
 6   Tenure           10001 non-null  int64
 7   EstimatedSalary  10001 non-null  str
dtypes: float64(1), int64(3), str(4)
memory usage: 625.2 KB
None
ACCOUNT INFO - DATA TYPES
<class 'pandas.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerId      10002 non-null  int64
 1   Balance         10002 non-null  str
 2   NumOfProducts   10002 non-null  int64
 3   HasCrCard       10002 non-null  str
 4   Tenure          10002 non-null  int64
 5   IsActiveMember  10002 non-null  str
 6   Exited          10002 non-null  int64
dtypes: int64(4), str(3)
memory usage: 547.1 KB
None

In [9]:
print("CUSTOMER INFO - MISSING VALUES")
print(customer_df.isnull().sum())

print("ACCOUNT INFO - MISSING VALUES")
print(account_df.isnull().sum())

CUSTOMER INFO - MISSING VALUES
CustomerId         0
Surname            3
CreditScore        0
Geography          0
Gender             0
Age                3
Tenure             0
EstimatedSalary    0
dtype: int64
ACCOUNT INFO - MISSING VALUES
CustomerId        0
Balance           0
NumOfProducts     0
HasCrCard         0
Tenure            0
IsActiveMember    0
Exited            0
dtype: int64

In [10]:
print("CUSTOMER INFO")
print("Duplicated rows", customer_df.duplicated().sum())
print("Duplicate Customer ID's:", customer_df["CustomerId"].duplicated().sum())

print("\nACCOUNT INFO")
print("Duplicated rows", account_df.duplicated().sum())
print("Duplicate Customer ID:", account_df["CustomerId"].duplicated().sum())

CUSTOMER INFO
Duplicated rows 1
Duplicate Customer ID's: 1

ACCOUNT INFO
Duplicated rows 2
Duplicate Customer ID: 2